#
# Copyright (c) 2025 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

SB_CONFIG_MATTER=y

# Factory Data 생성 비활성화
SB_CONFIG_MATTER_FACTORY_DATA_GENERATE=n
SB_CONFIG_MATTER_FACTORY_DATA_MERGE_WITH_FIRMWARE=n